# Generated by Django 5.0.6 on 2024-05-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('localisation', models.CharField(max_length=1000)),
                ('photo', models.ImageField(upload_to='supermarket')),
                ('is_activate', models.BooleanField(default=True)),
            ],
        ),
    ]
