# Generated by Django 5.0.6 on 2024-05-21 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('supermarket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supermarket.supermarket'),
        ),
    ]
